controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names:
        - front_left_wheel_joint
        - rear_left_wheel_joint
      right_wheel_names:
        - front_right_wheel_joint
        - rear_right_wheel_joint
      wheel_separation: 0.5  # 💡 Small tune here
      wheel_radius: 0.08
      cmd_vel_timeout: 0.25
      publish_rate: 50.0
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true
      open_loop: false
      velocity_rolling_window_size: 10
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 1.0
          min_velocity: -1.0
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 1.5
          min_velocity: -1.5
